[profile.release]
panic = 'unwind'

[workspace]
resolver = "2"
members = [
    'bench',
    'browser-testing',
    'cli',
    'test-runner-example',
    'executor',
    'primitives',
    'rpc',
    'rpc-client',
    'runtime',
    'staking',
    'testing',
]
